name: Release Stepp Backend Github Action
on:
  push:
    branches:
      - release
jobs:
  deploy-release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'release'
    steps:
      - run: echo "Hi from github action release deploy"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.2
      - name: Tidy and Vendor
        run: go mod tidy && go mod vendor
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
